permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# Blogger's information
author: 
  name: H.Y. ZHAN
  email: zhanhuangying@gmail.com
  link: https://huangying-zhan.github.io/
  # weibo: http://weibo.com/orangeissweet
  github: https://github.com/Huangying-Zhan
  # music: http://site.douban.com/linanya
  # linkedin: https://www.linkedin.com/

# Website's inforamtion
title: Huangying's Blog
description: My personal blog
url: https://huangying-zhan.github.io/
rss_url: /pages/atom.xml

# gavatar profile picture and Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics setup
ga:
  # id: UA-54262064-1 
  # url: painterlin.com

# disqus setup
disqus:
  shortname: H.Y. Zhan

# 主题设置，自动激活某个标签
active: UAV

# 首页除了最新文章外显示分类
cates: 
  - Setup

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档